A little bit messy, use with coution ...

diff --git a/crypto/crc b/crypto/crc
--- a/crypto/crc
+++ b/crypto/crc
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-mode=9
-verbose=1 #Detailed Errors
+mode=10 # Use with coaution ..
+verbose=2 #Debug
 cmd="2"
 if [ ! -c /dev/cryptotest ]; then
 	./dotestdev
@@ -9,28 +9,34 @@ fi
 
 text_bytes=$(( $(sudo cat /sys/kernel/debug/cryptotest/text | cut -d ' ' -f 1) ))
 
-if [ ! -z $1 ]; then
-	mode=$1
+if [ ! -z $3 ]; then
+	mode=$3
 fi
 
 #tid
+if [ ! -z $1 ]; then
+	cmd="$cmd,$1"
+else
+	if [ $text_bytes -eq 0 ]; then
+		cmd="$cmd,0" #One text in a shot please ...
+	else
+		cmd="$cmd,$(( $(sudo cat /sys/kernel/debug/cryptotest/text_id) - 1 ))"
+	fi
+fi
+
+#jid
 if [ ! -z $2 ]; then
 	cmd="$cmd,$2"
 fi
 
-#jid
-if [ ! -z $3 ]; then
-	cmd="$cmd,$3"
-fi
-
 case $mode in
-	9 | 10);;
-	*) echo "Bad mode found ($mode) for CRC, aborting." && exit 1;
+ 	10);;
+	*) echo "Bad mode found ($mode) for CRC, aborting." && exit 1; #Testing stage!
 esac
 
 if [ $text_bytes -eq 0 ]; then
    ./gentext $(( (RANDOM % 5) + 1))
-   cmd="2,0"
 fi
 
+echo "$cmd"
 sudo dmesg --clear && ./sendpar -v $verbose -m $mode && ./sendcmd "$cmd" && dmesg
