Partial

diff --git a/crypto/crc b/crypto/crc
--- a/crypto/crc
+++ b/crypto/crc
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-mode=3
+mode=9
 verbose=1 #Detailed Errors
-
+cmd="2"
 if [ ! -c /dev/cryptotest ]; then
 	./dotestdev
 fi
@@ -13,20 +13,24 @@ if [ ! -z $1 ]; then
 	mode=$1
 fi
 
+#tid
 if [ ! -z $2 ]; then
-	verbose=$2
+	cmd="$cmd,$2"
+fi
+
+#jid
+if [ ! -z $3 ]; then
+	cmd="$cmd,$3"
 fi
 
 case $mode in
-	3 | 4) key=8;;
-	5 | 6) key=16;;
-	7 | 8) key=24;;
-	
-	*) echo "Bad mode found ($mode) for DES variants, aborting." && exit 1;
+	9 | 10);;
+	*) echo "Bad mode found ($mode) for CRC, aborting." && exit 1;
 esac
 
 if [ $text_bytes -eq 0 ]; then
    ./gentext $(( (RANDOM % 5) + 1))
+   cmd="2,0"
 fi
 
-sudo dmesg --clear && ./sendpar -v $verbose -m $mode -k $key && ./sendcmd 1,2 && dmesg
+sudo dmesg --clear && ./sendpar -v $verbose -m $mode && ./sendcmd "$cmd" && dmesg
