Removed DDES mode.

diff --git a/crypto/tdes b/crypto/tdes
--- a/crypto/tdes
+++ b/crypto/tdes
@@ -19,17 +19,12 @@ fi
 
 case $mode in
 	3 | 4) key=8;;
-	5 | 6) key=16;;
-	7 | 8) key=24;;
-	*) key=""
+	5 | 6) key=24;;
+	*) echo "Bad mode found ($mode) for DES variants, aborting." && exit 1;
 esac
 
 if [ $text_bytes -eq 0 ]; then
    ./gentext $(( (RANDOM % 5) + 1))
 fi
 
-if [ ! -z $key ]; then
-   sudo dmesg --clear && ./sendpar -v $verbose -m $mode -k $key && ./sendcmd 1,2 && dmesg
-else
-	echo "Bad mode found ($mode) for DES variants, aborting."
-fi
+sudo dmesg --clear && ./sendpar -v $verbose -m $mode -k $key && ./sendcmd 1,2 && dmesg
